In [1]:
import numpy as np 


In [2]:
a=np.array([5,6,7])

In [3]:
a[0]

5

In [5]:
a=np.array([[1,2],[3,4],[5,6]])

In [6]:
a.ndim


2

In [7]:
a.itemsize

8

In [8]:
a.dtype

dtype('int64')

In [9]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a.shape

# 3 rows and 2 coloums

(3, 2)

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
l= range(5)
l

range(0, 5)

In [14]:
l[1]

1

In [15]:
np.arange(1,5)

array([1, 2, 3, 4])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [19]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a.shape

(3, 2)

In [21]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [23]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
aa=a.ravel()

In [25]:
aa

array([1, 2, 3, 4, 5, 6])

In [26]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.min()

1

In [28]:
a.max()

6

In [29]:
a.sum()

21

In [30]:
a.sum(axis=0)

array([ 9, 12])

In [31]:
a.sum(axis=1)

array([ 3,  7, 11])

In [32]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [33]:
np.std(a)

1.707825127659933