## linear regression with multiple variable 

----
- price = m1 * area + m2 * bedrooms + m3 * age + b
- y = m1x1 + m2x2 + m3x3 + b

In [1]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as pt 
from sklearn import linear_model

In [2]:
# load our data

df= pd.read_csv("homeprices2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math 
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

3

In [6]:
# data preprocessing step fill the empty value with median 
df.bedrooms=df.bedrooms.fillna(median_bedroom)
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
# before machine learning you need pre process data clean alll data 

reg= linear_model.LinearRegression()

In [8]:
#creating training set 

reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
reg.coef_
#cofienctet
#this is all value of m1 m2 m3 

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
reg.intercept_
# this our intercept  (b)


383724.9999999998

# now  we can calculate price 

#### we have this price about lets calculculate 
 - #1. 3000sqr area, 3 bedrooms , 40 year old 
- #2. 2500 sqr area, 4 beadrooms , 5 year old 


In [12]:

reg.predict([[3000,3,40]])

array([444400.])

In [14]:
# lets find out how its work 

#- price = m1 * area + m2 * bedrooms + m3 * age + b
#- y = m1x1 + m2x2 + m3x3 + b

137.25*3000+-26025*3+ -6825.*40+383724.9999999998

444399.9999999998

In [15]:
reg.predict([[2500,4,5]])

array([588625.])