In [1]:
# 1. - pickle
# 2. - sklearn joblib 

# 1, training model and find solution 

import pandas as pd 
import numpy as np 
from sklearn import linear_model


In [2]:
df  = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

array([859554.79452055])

In [8]:
import pickle
# saving our model in file format 

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)
    
    

In [14]:
# now we using this model in write format
with open('model_pickle','rb') as f:
    mp=pickle.load(f)
    



In [15]:
mp.predict([[5000]])

array([859554.79452055])

In [16]:
# it working now as like this we save our model in file format we can share it with our friends also using pickle 

In [20]:
from sklearn.externals import joblib


ImportError: cannot import name 'joblib' from 'sklearn.externals' (/home/nuke/anaconda3/lib/python3.9/site-packages/sklearn/externals/__init__.py)

In [21]:
import joblib

In [22]:
joblib.dump(model,'model_joblib')
# we save model here 

['model_joblib']

In [24]:
#now we gonna load our save model 

mj = joblib.load ('model_joblib')

In [26]:
mj.predict([[5000]])

array([859554.79452055])